### ISSUE TITLE
Crash on self signed "certificate_bundle"

### ISSUE THREAD

**Issue by unbelauscht** [jobs62/opnsense_unbound_external-dns_webhook#1]
Hi,

I found the webhook v0.1.1 & v0.1.2 crashing:

```
thread 'main' panicked at src/main.rs:132:10:
2024-03-18T11:04:40.198062390+01:00 called `Result::unwrap()` on an `Err` value: Error { tag: Tag::Default, profile: Some(Profile(Uncased { string: "default" })), metadata: None, path: [], kind: MissingField("certificate_bundle"), prev: None }
2024-03-18T11:04:40.198068050+01:00 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

My Helm chart looks like this:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
      version: 6.x.x
  interval: 12h0m
  values:
    provider: webhook
    registry: noop
    extraArgs:
      webhook-provider-url: http://localhost:8800
    managedRecordTypesFilters:
      - A
    sources:
      - ingress
      - service
    sidecars:
      - name: opnsense-unbound-external-dns-webhook
        image: ghcr.io/jobs62/opnsense_unbound_external-dns_webhook:v0.1.2
        ports:
          - containerPort: 8800
            name: http
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: http
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: http
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 5
        env:
          - name: OPNSENSE_BASE
            value: "https://192.168.40.254/"
          - name: OPNSENSE_ALLOW_INVALID_CERTS
            value: "true"
          - name: OPNSENSE_DOMAIN_FILTERS
            value: "[\"exmaple.com\"]"
          - name: OPNSENSE_KEY
            valueFrom:
              secretKeyRef:
                name: opnsense-api
                key: key
          - name: OPNSENSE_SECRET
            valueFrom:
              secretKeyRef:
                name: opnsense-api
                key: secret
```

Do you want a full stack trace? I also disabled the probes, since they wouldn't become healthy, but the webhook still works.
